config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions"}

  root to: 'pages#home'

  resource :customers
  resources :courses do
    resources :payments, only: [:new, :create]
    collection do
      get 'preview'
    end
  end
  resources :movers do
    collection do
      get 'confirmation'
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :mover
  belongs_to :customer
  has_many :sites, dependent: :destroy
  accepts_nested_attributes_for :sites, reject_if: :all_blank, allow_destroy: true
  # geocoded_by :pick_up_address
  # after_validation :geocode, if: :pick_up_address_changed?
  monetize :price_cents

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  def compute_infos

    pickup_address = self.sites.where(type_of: "pick_up").first.address
    drop_address = self.sites.where(type_of: "drop_off").first.address
    directions = GoogleDirections.new(pickup_address, drop_address)
    self.time = directions.drive_time_in_minutes
    self.kms = directions.distance_in_miles.fdiv(1.6)
    self.price = (40 + self.time * 0.6 + self.kms * 2)



  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :courses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/models/mover.rb
class Mover < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :trucks
  has_many :courses

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/



end

app/models/order.rb
class Order < ActiveRecord::Base
  monetize :amount_cents
  # validates :course_sku, presence: true
  validates :course_sku, uniqueness: true
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :course


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  belongs_to :mover

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :profile, polymorphic: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.profile = Customer.new(
        first_name: auth.info.first_name,
        last_name: auth.info.last_name,
        picture: auth.info.image.gsub('http://', 'https://'))
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: :preview

  def index
    if current_user.profile_id?
      @courses = Course.all
    elsif current_user.profile_type == "customer" || current_user.profile_type == "Customer"
      redirect_to new_customers_path
    else
      redirect_to new_mover_path
    end
  end

  def show
    @course = Course.find(params[:id])
    # TODO CALCUL DU PRIX SECURISE
    @markers = Gmaps4rails.build_markers(@course) do |course, marker|
      marker.lat @course.sites.first.latitude
      marker.lng @course.sites.first.longitude
    end
  end

  def new
    @course = Course.new
    @course.sites.build
  end

  def create
    @course = Course.create(course_params)
    if user_signed_in?  && current_user.profile && current_user.profile_type == "Customer"
      @course.customer = current_user.profile
    end

    @course.sku = "course_" + @course.id.to_s
    @course.status = "pending"
    # Set kms / time / price using Google API
    @course.compute_infos

    if @course.save
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def preview
    @course = Course.create(course_params)
    @course.sku = "course_" + @course.id.to_s
    @course.status = "pending"

    # Set kms / time / price using Google API
    @course.compute_infos

    redirect_to root_path unless @course.save
  end

  private

  def course_params
    params.require(:course).permit(
      :mover_rating,
      :from,
      :picture,
      :bucket,
      :status,
      :description,
      :customer_id,
      sites_attributes: [ :address, :type_of ],
    )
  end

end

app/controllers/movers_controller.rb
class MoversController < ApplicationController


  def show
    @mover = current_user.profile
  end

  def new
    @mover = Mover.new
  end

  def create
    @mover = Mover.new(mover_params)
    @mover.user = current_user
    @mover.status = false
    if @mover.save
      redirect_to confirmation_movers_path
    else
      render :new
    end
  end

  def edit
    @mover = current_user.profile
  end

  def update
    @mover = current_user.profile
    if @mover.update(mover_params)
      redirect_to mover_path(@mover)
    else
      render :edit
    end
  end


  def confirmation

  end

  private

  def mover_params
    params.require(:mover).permit(:first_name, :last_name, :phone_number,
      :picture, :status )
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.where(state: 'paid').find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    order = Order.create!(course_sku: @course.sku, amount: @course.price, state: 'pending')
    redirect_to new_order_payment_path(order)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout "static"

  def home
    @course = Course.new
    @course.sites.build
    if current_user && current_user.provider == "facebook"
      redirect_to new_course_path
    elsif current_user && current_user.profile_type == "Mover"
      current_mover = Mover.find(current_user.profile_id)
      if current_mover.status == true
        redirect_to courses_path
      else
        redirect_to confirmation_movers_path
      end
    end
  end

  private

  def course_params
    params.require(:course).permit(:mover_rating)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_course

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email: params[:stripeEmail]
    )
    # You should store this customer id and re-use it.

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount:       @course.price_cents,  # in cents
      description:  "Payment for course #{@course.sku} for order #{@course.id}",
      currency:     'eur'
    )

    @course.update(payment: charge.to_json, status: 'paid')

    redirect_to customers_path(current_user)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_course_payment_path(@course)
  end

  private

  def set_course
    @course = Course.where(status: 'pending').find(params[:course_id])
  end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movers_helper.rb
module MoversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movers/confirmation.html.erb
<div class = "text-center" >
  <h1> Welcome to the process of being a Gerard</h1>
  <h3> Your registration is in progress...</h3>
  <p> You will receive an email when you registration will be confirmed</p>
</div>

app/views/movers/edit.html.erb
<h2 class ="text-center">Profile page</h2>


<%= simple_form_for(@mover) do |f| %>
  <%= f.error_notification %>
  <div class ="text-center">
    <%= image_tag @mover.picture.url(:medium), class: "img-rounded" %>
  </div>


  <div class="col-xs-6">
    <%= f.input :first_name, placeholder: "Votre prénom" , label: "Prénom"%>
  </div>

  <div class="col-xs-6">
    <%= f.input :last_name, placeholder: "Votre nom", label: "Nom"%>
  </div>

  <div class="col-xs-12">
    <%=f.input :phone_number, placeholder:"Pour être contacté par le mover", label: "Téléphone"%>
  </div>

  <div class="col-xs-12 text-center">
    <h4>Votre email :  <%= current_user.email %></h4>
  </div>

  <div class="col-xs-12">
    <h4><%= f.input :picture%></h4>
  </div>

  <div class="col-xs-12 text-center">
      <%= f.button :submit %>
  </div>
<% end %>

app/views/movers/new.html.erb
<h2 class ="text-center">Profile page mover</h2>

<%= simple_form_for(@mover) do |f| %>
  <%= f.error_notification %>
  <div class = "text-center">
    <%= image_tag @mover.picture.url(:medium) %>
  </div>

  <div class="col-xs-6">
    <%= f.input :first_name, placeholder: "Votre prénom" , label: "Prénom"%>
  </div>

  <div class="col-xs-6">
    <%= f.input :last_name, placeholder: "Votre nom", label: "Nom"%>
  </div>

  <div class="col-xs-12">
    <%=f.input :phone_number, placeholder:"Pour être contacté par le client", label: "Téléphone"%>
  </div>

  <div class="col-xs-12 text-center">
    <h4>Votre email :  <%= current_user.email %></h4>
  </div>

  <div class="col-xs_12">
   <%= f.input :picture , label: "photo de profile"%>
  </div>

  <div class="col-xs_12">
     <%= f.input :picture , label: "photo de votre permis de conduire"%>
  </div>

  <div class="col-xs_12">
     <%= f.input :picture , label: "photo de la carte grise du véhicule"%>
  </div>

  <div class="col-xs-12 text-center">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/movers/show.html.erb
<div class = "text-center">
  <div class="card">
    <h1>Profil</h1>
    <span class="card-bg"></span>
    <span class="card-shadow"></span>
    <span class="card-description"><%= @mover.first_name.capitalize %></span>
    <span class="card-text">
      <%= simple_form_for (@mover), class: "form-horizontal" do |f| %>
        <span class="card-user">
          <%= image_tag @mover.picture.url(:thumb), class: "img-rounded",  style: "margin: 30px;" %>
        </span>

        <div class = "form-group">
          <div class="col-xs-6 control-label">First-Name:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @mover.first_name.capitalize %></p>
          </div>

          <div class="col-xs-6 control-label">Last-Name:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @mover.last_name.capitalize %></p>
          </div>

          <div class="col-xs-6 control-label">Phone-Number:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @mover.phone_number %></p>
          </div>

          <div class="col-xs-6 control-label">Profile Created At:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@mover.created_at.day%>/
            <%=@mover.created_at.month%>/
            <%=@mover.created_at.year%>
          </p>
          </div>

          <div class="col-xs-6 control-label">Driving License:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@mover.driving_license_number%>
          </p>
          </div>

          <div class="col-xs-6 control-label">ID Number:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @mover.identification_document_number %>
          </p>
          </div>

          <div class="col-xs-6 control-label">Last Update:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@mover.updated_at.day%>/
            <%=@mover.updated_at.month%>/
            <%=@mover.updated_at.year%>
          </p>
          </div>

          <div class="col-xs-6 control-label">Last Update:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@mover.updated_at.day%>/
            <%=@mover.updated_at.month%>/
            <%=@mover.updated_at.year%>
          </p>
          </div>

        </div>
        <div class="banner-btn">
          <%= link_to "Edit", edit_mover_path(@mover), class: "btn btn-warning" %>
        </div>
      <% end %>
    </span>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Order</h1>
<ul>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.course_sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>