config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions"}

  root to: 'pages#home'

  resource :customers
  resources :courses do
    resources :payments, only: [:new, :create]
    collection do
      get 'preview'
    end
  end
  resources :movers do
    collection do
      get 'confirmation'
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :mover
  belongs_to :customer
  has_many :sites, dependent: :destroy
  accepts_nested_attributes_for :sites, reject_if: :all_blank, allow_destroy: true
  # geocoded_by :pick_up_address
  # after_validation :geocode, if: :pick_up_address_changed?
  monetize :price_cents

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  def compute_infos

    pickup_address = self.sites.where(type_of: "pick_up").first.address
    drop_address = self.sites.where(type_of: "drop_off").first.address
    directions = GoogleDirections.new(pickup_address, drop_address)
    self.time = directions.drive_time_in_minutes
    self.kms = directions.distance_in_miles.fdiv(1.6)
    self.price = (40 + self.time * 0.6 + self.kms * 2)



  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :courses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/models/mover.rb
class Mover < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :trucks
  has_many :courses

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/



end

app/models/order.rb
class Order < ActiveRecord::Base
  monetize :amount_cents
  # validates :course_sku, presence: true
  validates :course_sku, uniqueness: true
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :course


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  belongs_to :mover

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :profile, polymorphic: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.profile = Customer.new(
        first_name: auth.info.first_name,
        last_name: auth.info.last_name,
        picture: auth.info.image.gsub('http://', 'https://'))
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: :preview

  def index
    if current_user.profile_id?
      @courses = Course.all
    elsif current_user.profile_type == "customer" || current_user.profile_type == "Customer"
      redirect_to new_customers_path
    else
      redirect_to new_mover_path
    end
  end

  def show
    @course = Course.find(params[:id])
    # TODO CALCUL DU PRIX SECURISE
    @markers = Gmaps4rails.build_markers(@course) do |course, marker|
      marker.lat @course.sites.first.latitude
      marker.lng @course.sites.first.longitude
    end
  end

  def new
    @course = Course.new
    @course.sites.build
  end

  def create
    @course = Course.create(course_params)
    if user_signed_in?  && current_user.profile && current_user.profile_type == "Customer"
      @course.customer = current_user.profile
    end

    @course.sku = "course_" + @course.id.to_s
    @course.status = "pending"
    # Set kms / time / price using Google API
    @course.compute_infos

    if @course.save
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def preview
    @course = Course.create(course_params)
    @course.sku = "course_" + @course.id.to_s
    @course.status = "pending"

    # Set kms / time / price using Google API
    @course.compute_infos

    redirect_to root_path unless @course.save
  end

  private

  def course_params
    params.require(:course).permit(
      :mover_rating,
      :from,
      :picture,
      :bucket,
      :status,
      :description,
      :customer_id,
      sites_attributes: [ :address, :type_of ],
    )
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :destroy, :update]

  def index
    @customers = Customer.all
    policy_scope(@customers)
  end

  def show
  end

  def new
    @customer = Customer.new
    authorize @customer
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.id = current_user
    current_user.profile_type = "Customer"
    current_user.save
    authorize @customer
    if @customer.save
      current_user.profile = @customer
      current_user.save
      redirect_to new_course_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @customer = current_user.profile
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy!
  end


  private

  def set_customer
    @customer = current_user.profile
    authorize @customer
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone_number, :picture)
  end

end

app/controllers/movers_controller.rb
class MoversController < ApplicationController


  def show
    @mover = current_user.profile
  end

  def new
    @mover = Mover.new
  end

  def create
    @mover = Mover.new(mover_params)
    @mover.user = current_user
    @mover.status = false
    if @mover.save
      redirect_to confirmation_movers_path
    else
      render :new
    end
  end

  def edit
    @mover = current_user.profile
  end

  def update
    @mover = current_user.profile
    if @mover.update(mover_params)
      redirect_to mover_path(@mover)
    else
      render :edit
    end
  end


  def confirmation

  end

  private

  def mover_params
    params.require(:mover).permit(:first_name, :last_name, :phone_number,
      :picture, :status )
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.where(state: 'paid').find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    order = Order.create!(course_sku: @course.sku, amount: @course.price, state: 'pending')
    redirect_to new_order_payment_path(order)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout "static"

  def home
    @course = Course.new
    @course.sites.build
    if current_user && current_user.provider == "facebook"
      redirect_to new_course_path
    elsif current_user && current_user.profile_type == "Mover"
      current_mover = Mover.find(current_user.profile_id)
      if current_mover.status == true
        redirect_to courses_path
      else
        redirect_to confirmation_movers_path
      end
    end
  end

  private

  def course_params
    params.require(:course).permit(:mover_rating)
  end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movers_helper.rb
module MoversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/edit.html.erb
<h2 class ="text-center">Votre profil</h2>

<%= simple_form_for @customer, url: customers_path, method: :post do |f| %>
  <%= f.error_notification %>
  <div class ="text-center">
    <%= image_tag @customer.picture.url(:medium), class: "img-rounded" %>
  </div>


  <div class="col-xs-6">
    <%= f.input :first_name, placeholder: "Votre prénom" , label: "Prénom"%>
  </div>

  <div class="col-xs-6">
    <%= f.input :last_name, placeholder: "Votre nom", label: "Nom"%>
  </div>

  <div class="col-xs-12">
    <%=f.input :phone_number, placeholder:"Pour être contacté par le mover", label: "Téléphone"%>
  </div>

  <div class="col-xs-12 text-center">
    <h4>Votre email :  <%= current_user.email %></h4>
  </div>

  <div class="col-xs-12">
    <h4><%= f.input :picture%></h4>
  </div>

  <div class="col-xs-12 text-center">
    <% if policy(@customer).update? %>
      <%= f.button :submit %>
    <% end %>
  </div>
<% end %>

app/views/customers/new.html.erb
<h2 class ="text-center">Profil</h2>

<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>
  <div class="col-xs-6">
    <%= f.input :first_name, placeholder: "Votre prénom" , label: "Prénom"%>
  </div>

  <div class="col-xs-6">
    <%= f.input :last_name, placeholder: "Votre nom", label: "Nom"%>
  </div>

  <div class="col-xs-12">
    <%=f.input :phone_number, placeholder:"Pour être contacté par le mover", label: "Téléphone"%>
  </div>

  <div class="col-xs-12 text-center">
    <h4>Votre email :  <%= current_user.email %></h4>
  </div>

  <div class="col-xs-12 text-center">
    <h4><%= f.file_field :picture %></h4>
  </div>

  <div class="col-xs-12 text-center">
    <% if policy(@customer).create? %>
      <%= f.button :submit %>
    <% end %>
  </div>
<% end %>

app/views/customers/show.html.erb
<div class = "text-center">
  <div class="card">
    <h1>Profil</h1>
    <span class="card-bg"></span>
    <span class="card-shadow"></span>
    <span class="card-description"><%= @customer.first_name.capitalize %> needs Gerard...</span>
    <span class="card-text">
      <%= simple_form_for (@customer), url: customers_path, class: "form-horizontal" do |f| %>
        <span class="card-user">
          <%= image_tag @customer.picture.url(:thumb), class: "img-rounded",  style: "margin: 30px;" %>
        </span>

        <div class = "form-group">
          <div class="col-xs-6 control-label">First-Name:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @customer.first_name.capitalize %></p>
          </div>

          <div class="col-xs-6 control-label">Last-Name:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @customer.last_name.capitalize %></p>
          </div>

          <div class="col-xs-6 control-label">Phone-Number:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%= @customer.phone_number %></p>
          </div>

          <div class="col-xs-6 control-label">Profile Created At:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@customer.created_at.day%>/
            <%=@customer.created_at.month%>/
            <%=@customer.created_at.year%>
          </p>
          </div>

          <div class="col-xs-6 control-label">Last Update:</div>
          <div class="col-xs-6">
          <p class="form-control-static"><%=@customer.updated_at.day%>/
            <%=@customer.updated_at.month%>/
            <%=@customer.updated_at.year%>
          </p>
          </div>

        </div>
        <div class="banner-btn">
          <%= link_to "Edit", edit_customers_path(@customer), class: "btn btn-warning" %>
        </div>
      <% end %>
    </span>
  </div>
</div>