config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions"}

  root to: 'pages#home'

  resource :customers
  resources :courses do
    resources :payments, only: [:new, :create]
    collection do
      get 'preview'
    end
  end
  resources :movers do
    collection do
      get 'confirmation'
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :mover
  belongs_to :customer
  has_many :sites, dependent: :destroy
  accepts_nested_attributes_for :sites, reject_if: :all_blank, allow_destroy: true
  # geocoded_by :pick_up_address
  # after_validation :geocode, if: :pick_up_address_changed?
  monetize :price_cents

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  def compute_infos

    pickup_address = self.sites.where(type_of: "pick_up").first.address
    drop_address = self.sites.where(type_of: "drop_off").first.address
    directions = GoogleDirections.new(pickup_address, drop_address)
    self.time = directions.drive_time_in_minutes
    self.kms = directions.distance_in_miles.fdiv(1.6)
    self.price = (40 + self.time * 0.6 + self.kms * 2)



  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :courses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/models/mover.rb
class Mover < ActiveRecord::Base
  has_one :user, as: :profile
  has_many :trucks
  has_many :courses

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/



end

app/models/order.rb
class Order < ActiveRecord::Base
  monetize :amount_cents
  # validates :course_sku, presence: true
  validates :course_sku, uniqueness: true
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :course


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/truck.rb
class Truck < ActiveRecord::Base
  belongs_to :mover

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :profile, polymorphic: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.profile = Customer.new(
        first_name: auth.info.first_name,
        last_name: auth.info.last_name,
        picture: auth.info.image.gsub('http://', 'https://'))
    end
  end

end

app/controllers/movers_controller.rb
class MoversController < ApplicationController


  def show
    @mover = current_user.profile
  end

  def new
    @mover = Mover.new
  end

  def create
    @mover = Mover.new(mover_params)
    @mover.user = current_user
    @mover.status = false
    if @mover.save
      redirect_to confirmation_movers_path
    else
      render :new
    end
  end

  def edit
    @mover = current_user.profile
  end

  def update
    @mover = current_user.profile
    if @mover.update(mover_params)
      redirect_to mover_path(@mover)
    else
      render :edit
    end
  end


  def confirmation

  end

  private

  def mover_params
    params.require(:mover).permit(:first_name, :last_name, :phone_number,
      :picture, :status )
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.where(state: 'paid').find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    order = Order.create!(course_sku: @course.sku, amount: @course.price, state: 'pending')
    redirect_to new_order_payment_path(order)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout "static"

  def home
    @course = Course.new
    @course.sites.build
    if current_user && current_user.provider == "facebook"
      redirect_to new_course_path
    elsif current_user && current_user.profile_type == "Mover"
      current_mover = Mover.find(current_user.profile_id)
      if current_mover.status == true
        redirect_to courses_path
      else
        redirect_to confirmation_movers_path
      end
    end
  end

  private

  def course_params
    params.require(:course).permit(:mover_rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movers_helper.rb
module MoversHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='<%= "#{params[:controller]}-#{params[:action]}".gsub('/', '-') %>'>
  <head>
    <title>GERARD</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= yield(:title) || "Your App name" %></title>
    <meta name="description" content="<%= (yield(:description) || "").squish %>">
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%#= render 'shared/notices' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerard</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= yield(:title) || "Your App name" %></title>
    <meta name="description" content="<%= (yield(:description) || "").squish %>">
  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%#= render 'shared/notices' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner text-center">
  <div class="top-right">
    <%= link_to "Se connecter", user_session_path, class: "btn btn-warning" %>
    <%= link_to "Devenir Gerard", new_user_registration_path + "?mover=true", class: "btn btn-info" %>
  </div>

  <div class="wrapper">
    <h1>Gerard,</h1>
      <div class="slogan">
        <hr>
        <h2 class="slidingVertical"><strong>transporte tes</strong>
        <span>armoires</span>
        <span>frigos</span>
        <span>sofas</span>
        <span>cartons</span>
      </div>
      </h2>
  </div>

  <div class="hidden-xs text-center">
    <p>Rejoignez nous sur notre application mobile</p>
  </div>

  <div class='form-home '>
    <%= simple_form_for @course, url: preview_courses_path, method: 'get' do |f| %>

      <%= f.fields_for :sites do |ff| %>
        <%= ff.input :address, placeholder: "Adresse de prise en charge", label: false %>
        <%= ff.hidden_field :type_of, value: "pick_up" %>

        <%= f.fields_for :sites do |ff| %>
          <%= ff.input :address, placeholder: "Adresse de dépôt",label: false %>
          <%= ff.hidden_field :type_of, value: "drop_off" %>
          <%= ff.hidden_field :from, value: "home" %>
        <br>
          <%= f.button :submit, "Estimation", class: "btn-home btn btn-primary" %>
        <% end %>
      <% end %>

    <% end %>
  </div>

</div>

<!-- Include Google Maps JS API -->
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDp6N1RFk7uGegeJBlNW9pKQmsY0ruzqDw "></script>

<!-- Custom JS code to bind to Autocomplete API -->
<script type="text/javascript" src="autocomplete.js"></script>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('input').keypress(function(e) {
        if(e.keyCode == '13') {
          e.preventDefault();
        }
      })
    })
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">
    <div class="btn-group">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="fa fa-bars" style="width: 500px;"></span></a>
          <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
             <li>
              <% if user_signed_in? %>
                <% if current_user.profile_type == "Customer" %>
                  <%= link_to customers_path do %>
                    <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                  <% end %>
                <% else %>
                  <%= link_to mover_path(current_user) do %>
                    <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                  <% end %>
                <% end %>
                <% else %>
                  <%= link_to t(".sign_in", default: "New?"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_course_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
      </div>
<!--
    <form action="" class="navbar-wagon-search hidden-xs">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->
<!--
    <% if user_signed_in? %>
      <%= link_to courses_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
        </div>
      <% end %>


    <% else %>
      <%= link_to t(".sign_in", default: "New?"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %> -->
  </div>


</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>